namespace salesngin.Models
{
    public class BaseModel
    {
        [Column("DateCreated")]
        [Display(Name = "Created")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MMM-yyyy}", NullDisplayText = "No Date")]
        public DateTime? DateCreated { get; set; }

        [Column("DateModified")]
        [Display(Name = "Modified")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MMM-yyyy}", NullDisplayText = "No Date")]
        public DateTime? DateModified { get; set; }

        [Column("CreatedBy")]
        [Display(Name = "Created By")]
        public int? CreatedBy { get; set; }

        [Column("ModifiedBy")]
        [Display(Name = "Modified By")]
        public int? ModifiedBy { get; set; }
        public bool IsDeleted { get; set; } = false;


        [ForeignKey("CreatedBy")]
        public ApplicationUser CreatedByUser { get; set; }

        [ForeignKey("ModifiedBy")]
        public ApplicationUser ModifiedByUser { get; set; }

        //A timestamp/rowversion is a property for which a new value is 
        //automatically generated by the database every time a row is inserted or updated. T
        //The property is also treated as a concurrency token, ensuring that you get an exception 
        //if a row you are updating has changed since you queried it.
        //[Timestamp]
        //public byte[] Timestamp { get; set; }
    }


    //Getting the current user logged in details 
    //var currentUsername = !string.IsNullOrEmpty(System.Web.HttpContext.Current?.User?.Identity?.Name)
    //        ? HttpContext.Current.User.Identity.Name
    //        : "Anonymous";

}
